services:
  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - '80:8080'
    volumes:
      - .:/var/www/tredo/test
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tredo
    depends_on:
      - db
      - app
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/tredo/test
      - /var/www/tredo/test/vendor
      - /var/www/tredo/test/docker/scripts
    networks:
      - tredo
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: '/data/tredo/test/db'
    volumes:
        - tredo_test_db:/data/tredo/test/db
    networks:
        - tredo
    ports:
        - '5432:5432'
networks:
  tredo:
    external: true
volumes:
  tredo_test_db:
    external: true
